### ISSUE TITLE
AI - Decide on a Vector Database

### ISSUE THREAD

**Issue by Nyumat** [OSU-App-Club/beavsAI-AI#4]

**Comment by sebat2004** [comment]
### What is a vector database? 
[Article](https://www.pinecone.io/learn/vector-database/)

**Comment by rahulvikram** [comment]
either pinecone or chroma seems to be the best choice

**Comment by sebat2004** [comment]
The officers discussed this, and Pinecone might be the way to go! Thanks for the suggestion @rahulvikram. We will have a little debrief on Pinecone and Vector DB's today to make sure everyone is on the same page.
